### ISSUE TITLE
Crash with mowzie's mobs (Forge 1.20.1)

### ISSUE THREAD

**Issue by CallieEZ** [nvb-uy/GeckoAnimFix#4]
This mod crashes with the new mowzie's mobs update, attached is a log of an instance running just embeddium, oculus, mowzie's mob's, geckolib, and this mod.

[latest.log](https://github.com/nvb-uy/GeckoAnimFix/files/15449962/latest.log)

**Comment by CallieEZ** [comment]
oop, forgot the crash report

[crash-2024-05-26_18.53.27-client.txt](https://github.com/nvb-uy/GeckoAnimFix/files/15449970/crash-2024-05-26_18.53.27-client.txt)

**Comment by nvb-uy** [comment]
looking into it

**Comment by AnyPruft** [comment]
[Render thread/FATAL] [mixin/]: Mixin apply failed mowziesmobs.mixins.json:GeoModelMixin -> software.bernie.geckolib.model.GeoModel: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @at("STORE" ordinal=0 index=-1) on software/bernie/geckolib/model/GeoModel::currentTimeInjected with priority 1000 cannot inject into software/bernie/geckolib/model/GeoModel::handleAnimations(Lsoftware/bernie/geckolib/core/animatable/GeoAnimatable;JLsoftware/bernie/geckolib/core/animation/AnimationState;)V merged by elocindev.geckoanimfix.mixin.common.GeoModelMixin with priority 1000 [PREINJECT Applicator Phase -> mowziesmobs.mixins.json:GeoModelMixin -> Prepare Injections -> -> localvar$bjg000$currentTimeInjected(DLsoftware/bernie/geckolib/core/animatable/GeoAnimatable;JLsoftware/bernie/geckolib/core/animation/AnimationState;)D -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @at("STORE" ordinal=0 index=-1) on software/bernie/geckolib/model/GeoModel::currentTimeInjected with priority 1000 cannot inject into software/bernie/geckolib/model/GeoModel::handleAnimations(Lsoftware/bernie/geckolib/core/animatable/GeoAnimatable;JLsoftware/bernie/geckolib/core/animation/AnimationState;)V merged by elocindev.geckoanimfix.mixin.common.GeoModelMixin with priority 1000 [PREINJECT Applicator Phase -> mowziesmobs.mixins.json:GeoModelMixin -> Prepare Injections -> -> localvar$bjg000$currentTimeInjected(DLsoftware/bernie/geckolib/core/animatable/GeoAnimatable;JLsoftware/bernie/geckolib/core/animation/AnimationState;)D -> Prepare]

**Comment by nvb-uy** [comment]
Was fixed from the mowzie's end
