### ISSUE TITLE
1.21 NeoForge | Version 1.0.1 of the mod saying its not for NeoForge

### ISSUE THREAD

**Issue by ChoccyMilch** [nvb-uy/GeckoAnimFix#6]
Every time i launch minecraft it tells me that the mod is just a forge mod, not a neoforge mod, even though it is listed as one on CurseForge.

**Comment by nvb-uy** [comment]
Yes, this is sadly a limitation of CurseForge itself.

The mod works on 1.21 FORGE, and NeoForge 1.20.1, but not NeoForge 1.21.
I cannot set a specific version and loader, CurseForge will assume it's compatible with all versions.

The mod will be updated to 1.21 neoforge soon, I'm currently super busy with some projects

**Comment by ChoccyMilch** [comment]
I understand, no problem. I was just confused is all, haha.

Good luck on your other projects! I will keep an eye on this repo for an update in the future.
