### ISSUE TITLE
Iris/Oculus & GeckoLib Compat

### ISSUE THREAD

**Issue by unablewillie** [nvb-uy/GeckoAnimFix#7]
I am trying to build a small pack for my friends, and I want to use shaders. It is neoforge 1.21. It says "File mods\GeckoLibOcculusCompat-Forge-1.01.jar is for Minecraft Forge or an older version of Neoforge, and cannot be loaded."

Is there anyway to fix this? None of the other shaders tools are updated to 1.21 but yours.

**Comment by nvb-uy** [comment]
That file works for NeoForge 1.20.1 only, or Forge 1.21

I'll be porting it to Neo 1.21 soon
