### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by GasterPollo** [nvb-uy/GeckoAnimFix#8]
[22ago.2024 12:30:25.704] [main/ERROR] [mixin/]: Mixin config geckoanimfix.forge.mixins.json does not specify "minVersion" property

It isn't a warning, it simply doesn't start

**Comment by nvb-uy** [comment]
Send the full log. Look below the log, that'll be the reason why it doesn't start. Instances that work just fine have this same log printed out yet they still work fine, because it's just a warning.

**Comment by nvb-uy** [comment]
duplicate of #5

**Comment by GasterPollo** [comment]
> Send the full log. Look below the log, that'll be the reason why it doesn't start. Instances that work just fine have this same log printed out yet they still work fine, because it's just a warning.

[Uploading latest.log…]()
